version: '3.7'

services:
  maildev:
    container_name: cool-mail
    image: maildev/maildev
    restart: always
    ports:
      - 1080:1080
      - 1025:1025

  db:
    container_name: cool-db
    image: 'postgres:14.6'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'

  redis:
    container_name: cool-redis
    image: redis
    ports:
      - '6379:6379'
    restart: always
